export const genreTranslate = {
  Action: { fa: "اکشن", en: "Action" },
  Adventure: { fa: "ماجراجویی", en: "Adventure" },
  Animation: { fa: "انیمیشن", en: "Animation" },
  Comedy: { fa: "کمدی", en: "Comedy" },
  Crime: { fa: "جنایی", en: "Crime" },
  Documentary: { fa: "مستند", en: "Documentary" },
  Drama: { fa: "درام", en: "Drama" },
  Family: { fa: "خانوادگی", en: "Family" },
  Fantasy: { fa: "فانتزی", en: "Fantasy" },
  History: { fa: "تاریخی", en: "History" },
  Horror: { fa: "وحشت", en: "Horror" },
  Music: { fa: "موزیک", en: "Music" },
  Mystery: { fa: "معمایی", en: "Mystery" },
  Romance: { fa: "عاشقانه", en: "Romance" },
  SciFi: { fa: "علمی تخیلی", en: "Sci-Fi" },
  Thriller: { fa: "دلهره‌آور", en: "Thriller" },
  War: { fa: "جنگی", en: "War" },
  Western: { fa: "وسترن", en: "Western" },
  Biography: { fa: "بیوگرافی", en: "Biography" },
  "Film-Noir": { fa: "فیلم / نوآر", en: "Film-Noir" },
  Sport: { fa: "ورزشی", en: "Sport" },
  "Sci-fi": { fa: "علمی-تخیلی", en: "Sci-fi" },
};
